### ISSUE TITLE
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. 

### ISSUE THREAD

**Issue by Johndirr** [YaoFANGUK/video-subtitle-extractor#45]
Running the vse_windows_GPU.7z version I get the error:

> RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
>   Suggestions:
>   1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
>   2. Configure third-party dynamic library environment variables as follows:
>   - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
>   - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release\paddle\fluid\platform\dynload\dynamic_loader.cc:265)

As far as I understand the dependencies are being installed when running the program the first time. I can also find the cudnn64_8.dll in the "vse\opt\CUDA" folder.

Is there anything I can do about this?

**Comment by YaoFANGUK** [comment]
Did you have the old version? you can replace all *.py files with the the ones.

**Comment by Johndirr** [comment]
I used 国外：vse_windows_GPU.7z (0.2.0)

**Comment by YaoFANGUK** [comment]
sorry for the late reply. maybe you can build from source code according to the README

**Comment by John-Smith-2020** [comment]
Same issue. Fixed by adding X:\Parent-Folder\vse\opt\CUDA to system PATH (in the Windows environmental variables settings).

**Comment by Johndirr** [comment]
> Same issue. Fixed by adding X:\Parent-Folder\vse\opt\CUDA to system PATH (in the Windows environmental variables settings).

Worked like a charm. Thank you.
